export const cardInfo = [
  {
    cardId: "card8",
    frontpage: true,
    cardHeader: "Four Cards Preview",
    stack: ["CSS", "HTML", "Javascript", "NEXT.js"],
    cardText: [
      "Very simple one page layout with 4 cards in it. ",
      "The challenge here was to get everything working with CSS Grid and I wanted to use Next.js to further learn the basic structure. ",
      "I also used mapping for Card object file to map trough it and get headers text and pictures to the cards this way. ",
      "This project as it was simple helped me to take what I have learned ",
      "from React to Next.js Next time I will further take what I know in React to Next.js",
    ],

    cardPicture: "/images/four_cards.jpg",
    github: "https://github.com/Jani-B/FEM-four-card-feature-nextjs",
    webpage: "https://janifourdcards.netlify.app/",
  },
  {
    cardId: "card7",
    frontpage: true,
    cardHeader: "My Portfolio Homepage",
    stack: ["CSS", "HTML", "Javascript", "NEXT.js"],
    cardText: [
      "This project was interesting. It was my first time working with ",
      "Next.js It took some time to learn all the Link, Client side etc rules. ",
      `This site is not the most complicated I have been working with `,

      "Challenge was that this was my first touch to Next.js asbefore I have been working with React. ",
      "There was some problems with the hamburger menu button on mobile view but I got it sorted out in the end. Next.js will be something I will be working with in the future also.",
    ],
    cardPicture: "/images/homepage.jpg",
    github: "https://github.com/Jani-B/portfolio_website",
    webpage: "https://www.janibergholm.com/",
  },
  {
    cardId: "card6",
    frontpage: true,
    cardHeader: "Rock - Paper - Scissors Game",
    stack: ["CSS", "HTML", "Javascript", "REACT"],
    cardText: [
      "This project was just small game of rock paper scissors. In the game ",
      "you can choose which 'weapon' you use and then you will see which ",
      "one your opponent chose. The game will also calculate wins.",
      "Project was done mobile first with React. The buttons on mobile ",
      "version are in the bottom of the screen after the first choise. It ",
      "should be easier to use that way. ",
    ],
    cardPicture: "/images/rockpaper.jpg",
    github: "https://github.com/Jani-B/rock-paper-game",
    webpage: "https://handsgame.netlify.app/",
  },
  {
    cardId: "card5",
    frontpage: true,
    cardHeader: "Mortgage calculator",
    stack: ["CSS", "HTML", "Javascript"],
    cardText: [
      "On this project you can calculate monthly payments with the total ",
      "loan, payment term in years and interest. Project was done using ",
      "HTML, CSS and Javascript. Tried to keep semantic HTML. Color of the ",
      "input field will change on focus and the result field will change in ",
      "different situations. Javascript was used to create different ",
      "results if for example not everything has been chosen correctly. If ",
      "everything in calculator has been marked correctly then it will ",
      "calculate with the given information. Created as a mobile first and ",
      "when screen size is bigger then the layout will change to work ",
      "better on the computer screens.",
    ],
    cardPicture: "/images/mortgage_calculator.jpg",
    github: "https://github.com/Jani-B/mortage_calculator",
    webpage: "https://jani-b.github.io/mortage_calculator/",
  },
  {
    cardId: "card4",
    frontpage: true,
    cardHeader: "Recipe page",
    stack: ["CSS", "HTML"],
    cardText: [
      "On this project I created a simple recipe page which has different ",
      "semantic sections. Project was more of a CSS training than not. It ",
      "is responsive and created as a mobile first approach. It is part of ",
      "FrontEnd Mentor challenges.",
    ],
    cardPicture: "/images/recipe-page.jpg",
    github: "https://github.com/Jani-B/FEM-recipe-page-main",
    webpage: "https://jani-b.github.io/FEM-recipe-page-main/",
  },
  {
    cardId: "card3",
    frontpage: false,
    cardHeader: "Blog Preview Card",
    stack: ["CSS", "HTML"],
    cardText: [
      "This was very basic practice project with CSS and HTML. With this I ",
      "was also practising how to code when given project on Figma file. ",
      "Project was simple but important for learnig also work with Figma.",
    ],
    cardPicture: "/images/blog-preview.jpg",
    github: "https://github.com/Jani-B/FEM_Blog_preview_card",
    webpage: "https://jani-b.github.io/FEM_Blog_preview_card/",
  },
  {
    cardId: "card2",
    frontpage: true,
    cardHeader: "Social Links Card",
    stack: ["CSS", "HTML"],
    cardText: [
      "This was once more one of the Frontend Mentor challenge projects for ",
      "CSS. Very simple project but was more to remind how different CSS ",
      "styles work. Also good small project to keep in mind updating to Github.",
    ],
    cardPicture: "/images/social_media_card.jpg",
    github: "https://github.com/Jani-B/FEM-social-links-profile",
    webpage: "https://jani-b.github.io/FEM-social-links-profile/",
  },
];
